# frozen_string_literal: true

# Carregamento manual dos módulos de scraping (excluídos do autoload Zeitwerk)
# para evitar conflitos de namespace (path scraping/ -> namespace ScrapingServices)
Rails.application.config.after_initialize do
  require Rails.root.join('lib/scraping/rate_limit_handler')
  require Rails.root.join('lib/scraping/services/rss_parser_service')
  require Rails.root.join('lib/scraping/services/youtube_scraper_service')
  require Rails.root.join('lib/scraping/python_bridge/sidecar_client')
  require Rails.root.join('lib/scraping/python_bridge/nodriver_runner')
  require Rails.root.join('lib/scraping/python_bridge/camoufox_service')
  require Rails.root.join('lib/scraping/python_bridge/curl_impersonate_client')
  require Rails.root.join('lib/scraping/services/http_stealth_client')
  require Rails.root.join('lib/scraping/services/tmdb_client')
  require Rails.root.join('lib/scraping/services/igdb_client')
  require Rails.root.join('lib/scraping/services/anilist_client')
  require Rails.root.join('lib/scraping/services/rawg_client')
  require Rails.root.join('lib/scraping/services/events_rss_parser')
  require Rails.root.join('lib/scraping/fetch_pacer')
  require Rails.root.join('lib/scraping/scrapers/ferrum_scraper_base')
  require Rails.root.join('lib/scraping/scrapers/instagram_scraper')
  require Rails.root.join('lib/scraping/scrapers/twitter_scraper')
  # LLM Integration (lib/llm — excluído do autoload Zeitwerk)
  require Rails.root.join('lib/llm/prompt_loader')
  require Rails.root.join('lib/llm/base_client')
  require Rails.root.join('lib/llm/gemini_background_client')
  require Rails.root.join('lib/llm/gemini_interactive_client')
  require Rails.root.join('lib/llm/openrouter_client')
end
